### ISSUE TITLE
更多空调支持集中回复帖

### ISSUE THREAD

**Issue by Becods** [BecodReyes/CJK_IR#1]
请在这里提你要支持的空调
仅限此贴跟楼回复，令开一贴**直接关闭**！
请确认[IRremoteESP8266](https://github.com/crankyoldgit/IRremoteESP8266)已支持，否则直接忽略！

**Comment by yeyun1999** [comment]
可以添加一下美的的支持吗？

**Comment by BecodReyes** [comment]
> 可以添加一下美的的支持吗？

代码正在重构，请稍等几天
